project:
  type: website

website:
  title: "ARSRL DigiEpi Workshop"
  navbar:
    logo: /img/dg_logo.jpg
    left: 
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: syllabus_new.qmd
        text: Syllabus  
      - href: speakers.qmd
        text: Resource Speakers
      - href: bioinformatics.qmd
        text: Concept Overview
      - text: Module
        menu:
          - module1/module1.qmd
          - module2/module2.qmd
          - module3/module3.qmd
          - module4/module4.qmd
      - text: Workshop Materials
        menu:
          - Pre_test.qmd
          - Post_test.qmd
          - Evaluation.qmd
      - href: https://forms.gle/24xz7CarkWZjTbrn6
        text: Got a question?


  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
    right: 
      - icon: twitter 
        href: https://twitter.com/TheCGPS


format:
  html:
    page-layout: full
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]
    anchor-sections: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
