project:
  type: website

website:
  title: "ARSRL DigiEpi Workshop"
  navbar:
    logo: /img/digiepi_logo.jpg
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: speakers.qmd
        text: Resource Speakers
      - href: bioinformatics.qmd
        text: Bioinformatics and Digital Epidemiology
      - text: Module
        menu:
          - module1/module1.qmd
          - resources.qmd
      - text: Pre-Test/Post-Test
      - text: Workshop Evaluation
      - text: Got a question?


  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 


format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]
    anchor-sections: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
