---
title: "Pre-test"
---

#### **Write the letter of the correct answer in the box before each number.**


* [  ]  1. SaTScan software allows for the detection of clusters based on:
a) Economic indicators
b) Population density only
c) Date and time alone
d) Spatial and temporal characteristics simultaneously

* [  ] 2. Which of the following is NOT a potential use of digital epidemiology tools during in outbreak
investigation?
a) Monitoring changes in resistance genes over time
b) Determining genetic relatedness among bacterial isolates
c) Predicting the atmospheric condition during the outbreak period
d) Identifying the source of the outbreak

* [  ] 3. Describe a scenario where the integration of SaTScan software and WGS would be beneficial in outbreak
response.
a) Identify clusters of antimicrobial resistance
b) Describe the genetic makeup of the drug-resistant bacteria
c) Identify genes that enable resistance and their transmission mechanisms
d) All of the above

* [  ] 4. Which of the following is an example of a digital epidemiology tool?
a) STATA
b) Microreact
c) SPSS
d) All of the above

* [  ] 5. How can digital epidemiology tools aid in the early detection of outbreaks?
a) By increasing reliance on paper-based data collection forms
b) By providing rapid data collection and analysis
c) By slowing down data analysis processes
d) By limiting data sharing capabilities

* [  ] 6. Which digital epidemiology tool is most suitable for monitoring changes in antimicrobial resistance
patterns over time?
a) Microreact
b) Epicollect
c) Pathogenwatch
d) STATA

* [  ] 7. How can Epicollect aid in antimicrobial resistance surveillance?
a) By analyzing genetic sequences
b) By performing virtual laboratory analyses
c) By collecting data on antimicrobial usage
d) By providing laboratory guidelines on antimicrobial susceptibility testing

* [  ] 8. In what way can Microreact enhance outbreak investigations?
a) By performing virtual laboratory tests
b) By providing laboratory guidelines on antimicrobial susceptibility testing
c) By providing statistical analyses including Chi-square test
d) By providing real-time visualization of pathogen spread

* [  ] 9. How do Epicollect, Pathogenwatch, and Microreact differ in terms of their primary functionalities?
a) Epicollect focuses on data visualization, Pathogenwatch on data collection, and
Microreact on genomic analysis
b) Epicollect focuses on genomic analysis, Pathogenwatch on data visualization, and Microreact
on data collection
c) Epicollect focuses on data collection, Pathogenwatch on genomic analysis, and Microreact on
data visualization

* [  ] 10. SaTScan is embedded in ____, which is a laboratory data management system utilized across ARSP
sentinel sites.
a) Epicollect
b) Pathogenwatch
c) STATA
d) WHONET